Ejercicio 1

Crea una array de numpy con los siguiente números primos: 2, 3, 5, 7, 11, 13, 17, 19, 23, 29

- Muestra el último elemento. Y debes hacerlo sin saber su longitud.
- Muestra el 3º elemento
- Muestra el último y 3º elemento.
- Muestra del 2º al 5º elemento.
- Muestra el 2° y el 5° elemento
- Muestra el último y el penúltimo elemento. Y debes hacerlo sin saber su longitud.


In [15]:
import numpy as np
# Crear el array de números primos
primos = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29])
# Mostrar el último elemento sin saber la longitud
ultimo_elemento = primos[-1]
print(ultimo_elemento)

29


In [16]:
import numpy as np
# Crear el array de números primos
primos = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29])
# Mostrar el tercer elemento sin saber la longitud
tercer_elemento = primos[2]
print(tercer_elemento)

5


In [17]:
import numpy as np
# Crear el array de números primos
primos = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29])
# Mostrar el último y el tercer elemento
ultimo_y_tercero = primos[[-1, 2]]
print(ultimo_y_tercero)


[29  5]


In [18]:
import numpy as np
# Crear el array de números primos
primos = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29])
# Mostrar del 2º al 5º elemento (índices 1 al 4)
segundo_al_quinto = primos[1:5]
print(segundo_al_quinto)

[ 3  5  7 11]


In [19]:
import numpy as np
# Crear el array de números primos
primos = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29])
# Mostrar el 2º y el 5º elemento
segundo_y_quinto = primos[[1, 4]]
print(segundo_y_quinto)

[ 3 11]


In [20]:
import numpy as np
# Crear el array de números primos
primos = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29])
# Mostrar el último y el penúltimo elemento
ultimo_y_penultimo = primos[-2:]
print(ultimo_y_penultimo)

[23 29]


Ejercicio 2 
- Crea una array de numpy con los siguiente números primos: 2, 3, 5, 7, 11, 13, 17, 19, 23, 29 pero que el array sea de tipo "float" de 32 bits.
- Usando la función arange de numpy crea un array con los números del 100 al 200 pero sin incluir el 200. Muestra el resultado.
- Usando la función range estándar de Python crea un array con los números del 100 al 200 pero sin incluir el 200. Muestra el resultado. ¿Qué diferencia hay con arange?

In [21]:
import numpy as np
# Crear array números primos
primos = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]
# Crear el array de numpy de tipo float32
array_primos = np.array (primos, dtype=np.float32)
print (array_primos)

[ 2.  3.  5.  7. 11. 13. 17. 19. 23. 29.]


In [22]:
import numpy as np
# Crear un array con los números del 100 al 200 sin incluir el 200
array_numeros = np.arange(100, 200)
print(array_numeros)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]


In [23]:
import numpy as np
# Crear un rango de números del 100 al 200 sin incluir el 200
numeros = list(range(100, 200))
print(numeros)

[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199]


Ejercicio 3
- Crea la siguiente matriz:
1465
4173
2912
6311

- Muestra el elemento de la fila 2º y la columna 3º. Es el valor del 7.
- Muestra la 3º Fila
- Muestra la 2º Columna
- Muestra la 2º y 3º Columna
- Muestra la 2º y 3º Fila
- Muestra la última columna. Debe funcionar independientemente del número de columnas.
- Muestra la 2º y 4º Columna y la 1º y 3º fila

In [24]:
import numpy as np
# Crear la matriz como un array de Numpy
matriz = np.array([[1, 4, 6, 5],
                   [4, 1, 7, 3],
                   [2, 9, 1, 2],
                   [6, 3, 1, 1]])

print(matriz)

[[1 4 6 5]
 [4 1 7 3]
 [2 9 1 2]
 [6 3 1 1]]


In [25]:
# Acceder al elemento en la fila 2 y columna 3
elemento = matriz[1, 2]  # fila 1, columna 2 (fila 2, columna 3)
print(elemento)

7


In [27]:
# Acceder a la fila 3
elemento = matriz [2]
print(elemento)

[2 9 1 2]


In [30]:
# Acceder a la columna 2
elemento = matriz [:,1:2]
print(elemento)

[[4]
 [1]
 [9]
 [3]]


In [31]:
# Acceder a la columna 2 y 3
elemento = matriz [:,1:3]
print(elemento)

[[4 6]
 [1 7]
 [9 1]
 [3 1]]


In [32]:
# Acceder a la fila 2 y 3
elemento = matriz [1:3,:]
print(elemento)

[[4 1 7 3]
 [2 9 1 2]]


In [43]:
# Acceder a la ultima colunmna
elemento = matriz [:,-1:]
print(elemento)

[[5]
 [3]
 [2]
 [1]]


In [56]:
# Seleccionar la 2ª y 4ª columna
columnas_seleccionadas = matriz[:, [1, 3]]  # Índices 1 y 3
# Seleccionar la 1ª y 3ª fila
filas_seleccionadas = matriz[[0, 2], :]  # Índices 0 y 2
print("2ª y 4ª columna:")
print(columnas_seleccionadas)
print("\n1ª y 3ª fila:")
print(filas_seleccionadas)

2ª y 4ª columna:
[[4 5]
 [1 3]
 [9 2]
 [3 1]]

1ª y 3ª fila:
[[1 4 6 5]
 [2 9 1 2]]
