Ejercicio 1

Crea una array de numpy con los siguiente números primos: 2, 3, 5, 7, 11, 13, 17, 19, 23, 29

- Muestra el último elemento. Y debes hacerlo sin saber su longitud.
- Muestra el 3º elemento
- Muestra el último y 3º elemento.
- Muestra del 2º al 5º elemento.
- Muestra el 2° y el 5° elemento
- Muestra el último y el penúltimo elemento. Y debes hacerlo sin saber su longitud.


In [5]:
import numpy as np

primos = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29])

ultimo_elemento = primos[-1]
print(ultimo_elemento)

29


In [6]:
import numpy as np

primos = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29])

tercer_elemento = primos[2]
print(tercer_elemento)

5


In [ ]:
import numpy as np

primos = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29])

ultimo_y_tercero = primos[[-1, 2]]
print(ultimo_y_tercero)


[29  5]


In [ ]:
import numpy as np

primos = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29])

segundo_al_quinto = primos[1:5]
print(segundo_al_quinto)

[ 3  5  7 11]


In [ ]:
import numpy as np

primos = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29])

segundo_y_quinto = primos[[1, 4]]
print(segundo_y_quinto)

[ 3 11]


In [ ]:
import numpy as np

primos = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29])

ultimo_y_penultimo = primos[-2:]
print(ultimo_y_penultimo)

[23 29]


Ejercicio 2 
- Crea una array de numpy con los siguiente números primos: 2, 3, 5, 7, 11, 13, 17, 19, 23, 29 pero que el array sea de tipo "float" de 32 bits.
- Usando la función arange de numpy crea un array con los números del 100 al 200 pero sin incluir el 200. Muestra el resultado.
- Usando la función range estándar de Python crea un array con los números del 100 al 200 pero sin incluir el 200. Muestra el resultado. ¿Qué diferencia hay con arange?

In [ ]:
import numpy as np

primos = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

array_primos = np.array (primos, dtype=np.float32)
print (array_primos)

[ 2.  3.  5.  7. 11. 13. 17. 19. 23. 29.]


In [ ]:
import numpy as np

array_numeros = np.arange(100, 200)
print(array_numeros)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]


In [ ]:
import numpy as np

numeros = list(range(100, 200))
print(numeros)

[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199]


Ejercicio 3
- Crea la siguiente matriz:
1465
4173
2912
6311

- Muestra el elemento de la fila 2º y la columna 3º. Es el valor del 7.
- Muestra la 3º Fila
- Muestra la 2º Columna
- Muestra la 2º y 3º Columna
- Muestra la 2º y 3º Fila
- Muestra la última columna. Debe funcionar independientemente del número de columnas.
- Muestra la 2º y 4º Columna y la 1º y 3º fila

In [ ]:
import numpy as np
#
matriz = np.array([[1, 4, 6, 5],
                   [4, 1, 7, 3],
                   [2, 9, 1, 2],
                   [6, 3, 1, 1]])

print(matriz)

[[1 4 6 5]
 [4 1 7 3]
 [2 9 1 2]
 [6 3 1 1]]


In [ ]:

elemento = matriz[1, 2]  
print(elemento)

7


In [ ]:

elemento = matriz [2]
print(elemento)

[2 9 1 2]


In [ ]:

elemento = matriz [:,1:2]
print(elemento)

[[4]
 [1]
 [9]
 [3]]


In [ ]:

elemento = matriz [:,1:3]
print(elemento)

[[4 6]
 [1 7]
 [9 1]
 [3 1]]


In [ ]:

elemento = matriz [1:3,:]
print(elemento)

[[4 1 7 3]
 [2 9 1 2]]


In [ ]:

elemento = matriz [:,-1:]
print(elemento)

[[5]
 [3]
 [2]
 [1]]


In [ ]:

columnas_seleccionadas = matriz[:, [1, 3]]  

filas_seleccionadas = matriz[[0, 2], :]  
print("2ª y 4ª columna:")
print(columnas_seleccionadas)
print("n1ª y 3ª fila:")
print(filas_seleccionadas)

2ª y 4ª columna:
[[4 5]
 [1 3]
 [9 2]
 [3 1]]
n1ª y 3ª fila:
[[1 4 6 5]
 [2 9 1 2]]


Ejercicio 4
- El siguiente array contiene las temperaturas medias que ha hecho en Valencia en cada mes [10.2, 10.7, 13.3, 15.8, 19.3, 23.6, 26, 25.9, 22.8, 19.1, 13.9, 10.8 ]
- Muestra las temperaturas cuyo valor sea mayor que 20
- Muestra las temperaturas cuyo valor sea menor que 11
- Muestra las temperaturas cuyo valor sea mayor que 20 o menor que 11

In [7]:

temperaturas = [10.2, 10.7, 13.3, 15.8, 19.3, 23.6, 26.0, 25.9, 22.8, 19.1, 13.9, 10.8]


mayor_que_20 = [temp for temp in temperaturas if temp > 20]
print("Temperaturas mayores que 20:", mayor_que_20)

Temperaturas mayores que 20: [23.6, 26.0, 25.9, 22.8]


In [8]:

menor_que_11 = [temp for temp in temperaturas if temp < 11]
print("Temperaturas menores que 11:", menor_que_11)

Temperaturas menores que 11: [10.2, 10.7, 10.8]


In [15]:

mayor_que_20_o_menor_que_11 = [temp for temp in temperaturas if temp > 20 or temp < 11]
print("Temperaturas mayores que 20 o menores que 11:", mayor_que_20_o_menor_que_11)

Temperaturas mayores que 20 o menores que 11: [10.2, 10.7, 23.6, 26.0, 25.9, 22.8, 10.8]


In [18]:
from sklearn.datasets import load_iris
datos=load_iris().data
resultado=load_iris().target

In [19]:

sepal_length = datos[:99, 0]
sepal_length

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1])

In [20]:
# Crear un array llamado petal_length con las 99 primeras filas y la 3ª columna de la matriz datos
petal_length = datos[:99, 2]
petal_length

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.4, 1.3,
       1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.6, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. ])

In [21]:
# Crear un array llamado x juntando las 2 columnas sepal_length y petal_length
x = np.column_stack((sepal_length, petal_length))
x

array([[5.1, 1.4],
       [4.9, 1.4],
       [4.7, 1.3],
       [4.6, 1.5],
       [5. , 1.4],
       [5.4, 1.7],
       [4.6, 1.4],
       [5. , 1.5],
       [4.4, 1.4],
       [4.9, 1.5],
       [5.4, 1.5],
       [4.8, 1.6],
       [4.8, 1.4],
       [4.3, 1.1],
       [5.8, 1.2],
       [5.7, 1.5],
       [5.4, 1.3],
       [5.1, 1.4],
       [5.7, 1.7],
       [5.1, 1.5],
       [5.4, 1.7],
       [5.1, 1.5],
       [4.6, 1. ],
       [5.1, 1.7],
       [4.8, 1.9],
       [5. , 1.6],
       [5. , 1.6],
       [5.2, 1.5],
       [5.2, 1.4],
       [4.7, 1.6],
       [4.8, 1.6],
       [5.4, 1.5],
       [5.2, 1.5],
       [5.5, 1.4],
       [4.9, 1.5],
       [5. , 1.2],
       [5.5, 1.3],
       [4.9, 1.4],
       [4.4, 1.3],
       [5.1, 1.5],
       [5. , 1.3],
       [4.5, 1.3],
       [4.4, 1.3],
       [5. , 1.6],
       [5.1, 1.9],
       [4.8, 1.4],
       [5.1, 1.6],
       [4.6, 1.4],
       [5.3, 1.5],
       [5. , 1.4],
       [7. , 4.7],
       [6.4, 4.5],
       [6.9,

In [22]:
# Crear un array llamado y con las 99 primeras filas del vector resultado
y = resultado[:99]
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Ejercicio 6
- Carga los datos del ejemplo de las flores con el siguiente código:

from sklearn.datasets import load_iris

datos=load_iris().data

resultado=load_iris().target

- Crea un array llamado x con las 99 primeras filas , la 1º columna y la 3º columna de la matriz datos
- Crea un array llamado y con las 99 primeras filas del vector resultado

In [35]:
from sklearn.datasets import load_iris
datos=load_iris().data
resultado=load_iris().target

In [36]:
# Crear un array llamado x con las 99 primeras filas, la 1ª columna y la 3ª columna de la matriz datos
x = datos[:99, [0, 2]]  # 0 es la 1ª columna (longitud del sépalo) y 2 es la 3ª columna (longitud del pétalo)
print("Array x:\n", x)

Array x:
 [[5.1 1.4]
 [4.9 1.4]
 [4.7 1.3]
 [4.6 1.5]
 [5.  1.4]
 [5.4 1.7]
 [4.6 1.4]
 [5.  1.5]
 [4.4 1.4]
 [4.9 1.5]
 [5.4 1.5]
 [4.8 1.6]
 [4.8 1.4]
 [4.3 1.1]
 [5.8 1.2]
 [5.7 1.5]
 [5.4 1.3]
 [5.1 1.4]
 [5.7 1.7]
 [5.1 1.5]
 [5.4 1.7]
 [5.1 1.5]
 [4.6 1. ]
 [5.1 1.7]
 [4.8 1.9]
 [5.  1.6]
 [5.  1.6]
 [5.2 1.5]
 [5.2 1.4]
 [4.7 1.6]
 [4.8 1.6]
 [5.4 1.5]
 [5.2 1.5]
 [5.5 1.4]
 [4.9 1.5]
 [5.  1.2]
 [5.5 1.3]
 [4.9 1.4]
 [4.4 1.3]
 [5.1 1.5]
 [5.  1.3]
 [4.5 1.3]
 [4.4 1.3]
 [5.  1.6]
 [5.1 1.9]
 [4.8 1.4]
 [5.1 1.6]
 [4.6 1.4]
 [5.3 1.5]
 [5.  1.4]
 [7.  4.7]
 [6.4 4.5]
 [6.9 4.9]
 [5.5 4. ]
 [6.5 4.6]
 [5.7 4.5]
 [6.3 4.7]
 [4.9 3.3]
 [6.6 4.6]
 [5.2 3.9]
 [5.  3.5]
 [5.9 4.2]
 [6.  4. ]
 [6.1 4.7]
 [5.6 3.6]
 [6.7 4.4]
 [5.6 4.5]
 [5.8 4.1]
 [6.2 4.5]
 [5.6 3.9]
 [5.9 4.8]
 [6.1 4. ]
 [6.3 4.9]
 [6.1 4.7]
 [6.4 4.3]
 [6.6 4.4]
 [6.8 4.8]
 [6.7 5. ]
 [6.  4.5]
 [5.7 3.5]
 [5.5 3.8]
 [5.5 3.7]
 [5.8 3.9]
 [6.  5.1]
 [5.4 4.5]
 [6.  4.5]
 [6.7 4.7]
 [6.3 4.4]
 [5.6 4.1]
 [5.5 4. ]


In [37]:

# Crear un array llamado y con las 99 primeras filas del vector resultado
y = resultado[:99]
print("Array y:\n", y)

Array y:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


Ejercicio 6
- Selecciona las celdas en rojo oscuro de la siguiente matriz:


In [ ]:
# Crear la matriz como un array de Numpy
matriz = np.array([[1, 2,  3,   4, 5,   6,  7, 8],
                   [9, 10, 11, 12, 13, 14, 15, 16]
                   [17,18, 19, 20, 21, 22, 23 ,24],
                   [25,26, 27, 28, 29, 30, 31, 32]])

Ejercicio 7
- Selecciona las celdas en rojo oscuro de la siguiente matriz:
- Ahora selecciona las celdas en rojo oscuro pero también las verdes y azules que hay por detrás de las rojo oscuro.

In [67]:
import numpy as np

# Crear una matriz 3D de 7 filas, 8 columnas y 1 capa
matriz_3d = np.random.rand(7, 8, 1)

submatriz = matriz_3d[0:1, 2:5, 2:6]
print (matriz_3d)

print("Submatriz seleccionada:\n", submatriz)

[[[0.09135743]
  [0.20503532]
  [0.23363909]
  [0.32200599]
  [0.01557741]
  [0.77961546]
  [0.82992384]
  [0.73861232]]

 [[0.95558669]
  [0.64782833]
  [0.17872204]
  [0.07229277]
  [0.89900526]
  [0.75989884]
  [0.88320471]
  [0.39824297]]

 [[0.74750646]
  [0.53572415]
  [0.38640445]
  [0.59863659]
  [0.08421832]
  [0.86683674]
  [0.90626752]
  [0.65637634]]

 [[0.00162272]
  [0.23883147]
  [0.96519785]
  [0.72515556]
  [0.71330748]
  [0.97577272]
  [0.28701642]
  [0.86393752]]

 [[0.87364757]
  [0.83854465]
  [0.76772003]
  [0.84858261]
  [0.48340405]
  [0.89411319]
  [0.32947651]
  [0.57455419]]

 [[0.20308741]
  [0.52562831]
  [0.43010172]
  [0.0344848 ]
  [0.02241397]
  [0.2400181 ]
  [0.03562642]
  [0.1480422 ]]

 [[0.10031948]
  [0.1210766 ]
  [0.95826324]
  [0.37130363]
  [0.36886719]
  [0.48056001]
  [0.91947494]
  [0.11250754]]]
Submatriz seleccionada:
 []


Ejercicio 8
Crea la siguiente matriz:

- A todos los elementos de la matriz sumale un 10. Usando las funciones de numpy
- A todos los elementos de la matriz sumale un 10 y divídelos entre 2. Usando las funciones de numpy
- A todos los elementos de la matriz sumale un 10. Usando operadores
- A todos los elementos de la matriz sumale un 10 y divídelos entre 2. Usando operadores


In [42]:
# Crear la matriz como un array de Numpy
matriz = np.array([[1, 4, 6, 5],
                   [4, 1, 7, 3],
                   [2, 9, 1, 2],
                   [6, 3, 1, 1]])

# 1. A todos los elementos de la matriz, súmale un 10 usando funciones de NumPy
matriz_suma_10_np = np.add(matriz, 10)
print("Matriz original:\n", matriz)

Matriz original:
 [[1 4 6 5]
 [4 1 7 3]
 [2 9 1 2]
 [6 3 1 1]]


In [43]:

# 2. A todos los elementos de la matriz, súmale un 10 y divídelos entre 2 usando funciones de NumPy
matriz_suma_10_div_2_np = np.divide(np.add(matriz, 10), 2)
print("Suma 10 usando NumPy:\n", matriz_suma_10_np)

Suma 10 usando NumPy:
 [[11 14 16 15]
 [14 11 17 13]
 [12 19 11 12]
 [16 13 11 11]]


In [44]:
# 3. A todos los elementos de la matriz, súmale un 10 usando operadores
matriz_suma_10_op = matriz + 10
print("Suma 10 usando operadores:\n", matriz_suma_10_op)

Suma 10 usando operadores:
 [[11 14 16 15]
 [14 11 17 13]
 [12 19 11 12]
 [16 13 11 11]]


In [45]:
# 4. A todos los elementos de la matriz, súmale un 10 y divídelos entre 2 usando operadores
matriz_suma_10_div_2_op = (matriz + 10) / 2
print("Suma 10 y divido entre 2 usando operadores:\n", matriz_suma_10_div_2_op)

Suma 10 y divido entre 2 usando operadores:
 [[5.5 7.  8.  7.5]
 [7.  5.5 8.5 6.5]
 [6.  9.5 5.5 6. ]
 [8.  6.5 5.5 5.5]]


Ejercicio 10
- Crea la siguiente matriz:

[[1 2 3]
 [4 5 6]
 [7 8 9]]

- Multiplica cada elemento de la matriz por sí mismo
- Multiplica la matriz por sí misma



In [50]:
# Crear la matriz especificada
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# 1. Multiplicar cada elemento de la matriz por sí mismo (elevar al cuadrado)
matriz_cuadrado = matriz ** 2
print("Cada elemento al cuadrado:\n", matriz_cuadrado)

Cada elemento al cuadrado:
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [51]:

# 2. Multiplicar la matriz por sí misma (multiplicación de matrices)
matriz_producto = np.dot(matriz, matriz)
print("Matriz multiplicada por sí misma:\n", matriz_producto)

Matriz multiplicada por sí misma:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


Ejercicio 10
- Crea una función llamada f que acepte como parámetro el número y que retorne el valor multiplicado por 2 y además que se le sume 1.
- Crea ahora el vector de numpy [1,5,4,7,3,9,8,6] y aplícale la función f


In [56]:
# Definir la función f
def f(x):
    return (x * 2) + 1

# Crear el vector de numpy
vector = np.array([1, 5, 4, 7, 3, 9, 8, 6])
# Aplicar la función f a cada elemento del vector
resultado = f(vector)
print(resultado)

[ 3 11  9 15  7 19 17 13]


Ejercicio 11
- Crea una función llamada f que acepte como parámetro el número y que retorne lo siguiente:
- Si es valor está en el rango (-inf,3] que retorne 0
- Si es valor está en el rango [3,5] que retorne 4
- Si es valor está en el rango [5,6] que retorne 5
- Si es valor está en el rango [6,7] que retorne 6
- Si es valor está en el rango [7,9] que retorne 8
- Si es valor está en el rango [9,+inf) que retorne 10
- Crea ahora el vector de numpy [1,5,4,7,3,9,8,6] y aplícale la función f


In [59]:
# Definir la función f según las condiciones especificadas
def f(x):
    if x <= 3:
        return 0
    elif 3 < x <= 5:
        return 4
    elif 5 < x <= 6:
        return 5
    elif 6 < x <= 7:
        return 6
    elif 7 < x <= 9:
        return 8
    elif x > 9:
        return 10

# Crear el vector de numpy
vector = np.array([1, 5, 4, 7, 3, 9, 8, 6])

# Aplicar la función f a cada elemento del vector
resultado = np.vectorize(f)(vector)

# Mostrar resultados
print(resultado)

[0 4 4 6 0 8 8 5]
